-- Catálogo base del sector (generado por scripts/gen-catalog.mjs)
insert into catalog_categories (id, name, singular, iva, kind, orden) values
  ('verdura', 'Verduras y hortalizas', 'verdura', 4, 'cocina', 1),
  ('fruta', 'Frutas', 'fruta', 4, 'cocina', 2),
  ('huevos', 'Huevos', 'huevo', 4, 'cocina', 3),
  ('leche_queso', 'Leche y quesos', 'leche o queso', 4, 'cocina', 4),
  ('pan_harina', 'Pan y harinas', 'pan o harina', 4, 'cocina', 5),
  ('legumbre_cereal', 'Legumbres, arroces y cereales', 'legumbre o cereal', 4, 'cocina', 6),
  ('aceite_oliva', 'Aceites de oliva', 'aceite de oliva', 4, 'cocina', 7),
  ('carne', 'Carnes y aves', 'carne', 10, 'cocina', 8),
  ('pescado', 'Pescados y mariscos', 'pescado o marisco', 10, 'cocina', 9),
  ('charcuteria', 'Embutidos y charcutería', 'embutido', 10, 'cocina', 10),
  ('lacteo', 'Lácteos y derivados', 'derivado lácteo', 10, 'cocina', 11),
  ('pasta', 'Pastas', 'pasta', 10, 'cocina', 12),
  ('aceite_otro', 'Otros aceites y grasas', 'aceite o grasa', 10, 'cocina', 13),
  ('conserva', 'Conservas', 'conserva', 10, 'cocina', 14),
  ('condimento', 'Condimentos, especias y vinagres', 'condimento', 10, 'cocina', 15),
  ('salsa', 'Salsas y preparados', 'salsa o preparado', 10, 'cocina', 16),
  ('reposteria', 'Azúcar, frutos secos y repostería', 'producto de repostería', 10, 'cocina', 17),
  ('congelado', 'Congelados', 'congelado', 10, 'cocina', 18),
  ('cafe', 'Café e infusiones', 'café o infusión', 10, 'bebida', 19),
  ('bebida', 'Aguas, refrescos y zumos', 'bebida sin alcohol', 10, 'bebida', 20),
  ('cerveza', 'Cervezas', 'cerveza', 21, 'bebida', 21),
  ('vino', 'Vinos, cavas y sidras', 'vino', 21, 'bebida', 22),
  ('licor', 'Licores y destilados', 'licor', 21, 'bebida', 23),
  ('limpieza', 'Limpieza y desechables', 'producto de limpieza', 21, 'otros', 24),
  ('otros', 'Otros', 'producto', 10, 'otros', 25)
on conflict (id) do update set name = excluded.name, singular = excluded.singular, iva = excluded.iva, kind = excluded.kind, orden = excluded.orden;

insert into catalog_items (id, name, category_id, unit, rend, aliases) values
  ('tomate-pera', 'Tomate pera', 'verdura', 'kg', 95, array['tomate']::text[]),
  ('tomate-rama', 'Tomate en rama', 'verdura', 'kg', 95, array[]::text[]),
  ('tomate-cherry', 'Tomate cherry', 'verdura', 'kg', 98, array[]::text[]),
  ('tomate-raf', 'Tomate raf', 'verdura', 'kg', 95, array[]::text[]),
  ('cebolla', 'Cebolla', 'verdura', 'kg', 90, array[]::text[]),
  ('cebolla-dulce', 'Cebolla dulce', 'verdura', 'kg', 90, array['cebolla fuentes']::text[]),
  ('cebolla-morada', 'Cebolla morada', 'verdura', 'kg', 90, array[]::text[]),
  ('cebolleta', 'Cebolleta', 'verdura', 'kg', 80, array[]::text[]),
  ('ajo', 'Ajo', 'verdura', 'kg', 85, array['ajos']::text[]),
  ('puerro', 'Puerro', 'verdura', 'kg', 70, array[]::text[]),
  ('zanahoria', 'Zanahoria', 'verdura', 'kg', 90, array[]::text[]),
  ('patata', 'Patata', 'verdura', 'kg', 85, array['patatas']::text[]),
  ('patata-agria', 'Patata agria', 'verdura', 'kg', 85, array[]::text[]),
  ('patata-nueva', 'Patata nueva', 'verdura', 'kg', 90, array[]::text[]),
  ('boniato', 'Boniato', 'verdura', 'kg', 85, array[]::text[]),
  ('pimiento-rojo', 'Pimiento rojo', 'verdura', 'kg', 85, array[]::text[]),
  ('pimiento-verde', 'Pimiento verde', 'verdura', 'kg', 85, array[]::text[]),
  ('pimiento-italiano', 'Pimiento italiano', 'verdura', 'kg', 85, array[]::text[]),
  ('pimiento-padron', 'Pimiento de Padrón', 'verdura', 'kg', 98, array[]::text[]),
  ('calabacin', 'Calabacín', 'verdura', 'kg', 95, array[]::text[]),
  ('berenjena', 'Berenjena', 'verdura', 'kg', 90, array[]::text[]),
  ('calabaza', 'Calabaza', 'verdura', 'kg', 75, array[]::text[]),
  ('pepino', 'Pepino', 'verdura', 'kg', 90, array[]::text[]),
  ('lechuga-romana', 'Lechuga romana', 'verdura', 'ud', 85, array['romana']::text[]),
  ('lechuga-iceberg', 'Lechuga iceberg', 'verdura', 'ud', 85, array[]::text[]),
  ('lechuga-variada', 'Lechuga variada', 'verdura', 'kg', 95, array['mezclum', 'mix ensalada']::text[]),
  ('brotes-tiernos', 'Brotes tiernos', 'verdura', 'kg', 98, array['brotes']::text[]),
  ('rucula', 'Rúcula', 'verdura', 'kg', 95, array[]::text[]),
  ('canonigos', 'Canónigos', 'verdura', 'kg', 95, array[]::text[]),
  ('espinaca', 'Espinaca', 'verdura', 'kg', 85, array['espinaca baby']::text[]),
  ('acelga', 'Acelga', 'verdura', 'kg', 80, array[]::text[]),
  ('brocoli', 'Brócoli', 'verdura', 'kg', 65, array[]::text[]),
  ('coliflor', 'Coliflor', 'verdura', 'kg', 60, array[]::text[]),
  ('repollo', 'Repollo', 'verdura', 'kg', 85, array[]::text[]),
  ('col-lombarda', 'Col lombarda', 'verdura', 'kg', 85, array[]::text[]),
  ('alcachofa', 'Alcachofa', 'verdura', 'kg', 40, array[]::text[]),
  ('esparrago-verde', 'Espárrago verde', 'verdura', 'kg', 70, array['esparrago triguero']::text[]),
  ('judia-verde', 'Judía verde', 'verdura', 'kg', 90, array[]::text[]),
  ('guisante', 'Guisante', 'verdura', 'kg', 100, array[]::text[]),
  ('champinon', 'Champiñón', 'verdura', 'kg', 95, array[]::text[]),
  ('setas-variadas', 'Setas variadas', 'verdura', 'kg', 90, array[]::text[]),
  ('seta-shiitake', 'Seta shiitake', 'verdura', 'kg', 90, array[]::text[]),
  ('apio', 'Apio', 'verdura', 'kg', 75, array[]::text[]),
  ('hinojo', 'Hinojo', 'verdura', 'kg', 70, array[]::text[]),
  ('jengibre', 'Jengibre', 'verdura', 'kg', 85, array[]::text[]),
  ('perejil', 'Perejil', 'verdura', 'ud', 80, array['manojo perejil']::text[]),
  ('cilantro', 'Cilantro', 'verdura', 'ud', 80, array[]::text[]),
  ('albahaca', 'Albahaca', 'verdura', 'ud', 80, array[]::text[]),
  ('hierbabuena', 'Hierbabuena', 'verdura', 'ud', 80, array['menta']::text[]),
  ('cebollino', 'Cebollino', 'verdura', 'ud', 90, array[]::text[]),
  ('guindilla', 'Guindilla', 'verdura', 'kg', 95, array[]::text[]),
  ('limon', 'Limón', 'fruta', 'kg', 100, array['limones']::text[]),
  ('lima', 'Lima', 'fruta', 'kg', 100, array[]::text[]),
  ('naranja', 'Naranja', 'fruta', 'kg', 100, array[]::text[]),
  ('naranja-zumo', 'Naranja de zumo', 'fruta', 'kg', 100, array[]::text[]),
  ('mandarina', 'Mandarina', 'fruta', 'kg', 100, array[]::text[]),
  ('manzana-golden', 'Manzana golden', 'fruta', 'kg', 85, array[]::text[]),
  ('manzana-reineta', 'Manzana reineta', 'fruta', 'kg', 85, array[]::text[]),
  ('pera', 'Pera conferencia', 'fruta', 'kg', 85, array[]::text[]),
  ('platano', 'Plátano de Canarias', 'fruta', 'kg', 70, array['platano']::text[]),
  ('fresa', 'Fresa', 'fruta', 'kg', 95, array[]::text[]),
  ('frambuesa', 'Frambuesa', 'fruta', 'kg', 100, array[]::text[]),
  ('arandano', 'Arándano', 'fruta', 'kg', 100, array[]::text[]),
  ('uva', 'Uva', 'fruta', 'kg', 95, array[]::text[]),
  ('melon', 'Melón', 'fruta', 'kg', 60, array[]::text[]),
  ('sandia', 'Sandía', 'fruta', 'kg', 55, array[]::text[]),
  ('pina', 'Piña', 'fruta', 'kg', 55, array[]::text[]),
  ('mango', 'Mango', 'fruta', 'kg', 70, array[]::text[]),
  ('kiwi', 'Kiwi', 'fruta', 'kg', 85, array[]::text[]),
  ('aguacate', 'Aguacate', 'fruta', 'kg', 70, array[]::text[]),
  ('melocoton', 'Melocotón', 'fruta', 'kg', 85, array[]::text[]),
  ('higo', 'Higo', 'fruta', 'kg', 95, array[]::text[]),
  ('granada', 'Granada', 'fruta', 'kg', 55, array[]::text[]),
  ('huevo-campero-l', 'Huevo campero L', 'huevos', 'ud', 100, array['huevos camperos', 'huevo l']::text[]),
  ('huevo-m', 'Huevo M', 'huevos', 'ud', 100, array['huevos m']::text[]),
  ('huevo-codorniz', 'Huevo de codorniz', 'huevos', 'ud', 100, array[]::text[]),
  ('huevo-liquido', 'Huevo líquido pasteurizado', 'huevos', 'L', 100, array['huevo liquido']::text[]),
  ('leche-entera', 'Leche entera', 'leche_queso', 'L', 100, array[]::text[]),
  ('leche-semi', 'Leche semidesnatada', 'leche_queso', 'L', 100, array[]::text[]),
  ('queso-manchego', 'Queso manchego curado', 'leche_queso', 'kg', 92, array['manchego']::text[]),
  ('queso-semicurado', 'Queso semicurado', 'leche_queso', 'kg', 95, array[]::text[]),
  ('queso-cabra', 'Queso de cabra en rulo', 'leche_queso', 'kg', 95, array['rulo de cabra']::text[]),
  ('mozzarella', 'Mozzarella', 'leche_queso', 'kg', 100, array[]::text[]),
  ('burrata', 'Burrata', 'leche_queso', 'ud', 100, array[]::text[]),
  ('parmesano', 'Queso parmesano', 'leche_queso', 'kg', 95, array['grana padano']::text[]),
  ('queso-azul', 'Queso azul', 'leche_queso', 'kg', 95, array[]::text[]),
  ('queso-crema', 'Queso crema', 'leche_queso', 'kg', 100, array[]::text[]),
  ('queso-rallado', 'Queso rallado', 'leche_queso', 'kg', 100, array[]::text[]),
  ('pan-barra', 'Pan de barra', 'pan_harina', 'ud', 100, array['barra de pan']::text[]),
  ('pan-hamburguesa', 'Pan de hamburguesa', 'pan_harina', 'ud', 100, array[]::text[]),
  ('pan-molde', 'Pan de molde', 'pan_harina', 'ud', 100, array[]::text[]),
  ('harina-trigo', 'Harina de trigo', 'pan_harina', 'kg', 100, array[]::text[]),
  ('harina-fuerza', 'Harina de fuerza', 'pan_harina', 'kg', 100, array[]::text[]),
  ('arroz-redondo', 'Arroz redondo', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('arroz-bomba', 'Arroz bomba', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('arroz-basmati', 'Arroz basmati', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('garbanzo', 'Garbanzo', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('lenteja', 'Lenteja', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('alubia-blanca', 'Alubia blanca', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('alubia-roja', 'Alubia roja', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('quinoa', 'Quinoa', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('copos-avena', 'Copos de avena', 'legumbre_cereal', 'kg', 100, array[]::text[]),
  ('aceite-oliva-ve', 'Aceite de oliva virgen extra', 'aceite_oliva', 'L', 100, array['aove', 'aceite oliva v extra', 'aceite oliva virgen extra']::text[]),
  ('aceite-oliva-suave', 'Aceite de oliva suave', 'aceite_oliva', 'L', 100, array['aceite oliva 0.4']::text[]),
  ('aceite-orujo', 'Aceite de orujo de oliva', 'aceite_oliva', 'L', 100, array[]::text[]),
  ('pollo-entero', 'Pollo entero', 'carne', 'kg', 100, array[]::text[]),
  ('pechuga-pollo', 'Pechuga de pollo', 'carne', 'kg', 95, array[]::text[]),
  ('muslo-pollo', 'Muslo de pollo', 'carne', 'kg', 90, array[]::text[]),
  ('alitas-pollo', 'Alitas de pollo', 'carne', 'kg', 100, array[]::text[]),
  ('contramuslo-pollo', 'Contramuslo de pollo deshuesado', 'carne', 'kg', 95, array[]::text[]),
  ('pavo-pechuga', 'Pechuga de pavo', 'carne', 'kg', 95, array[]::text[]),
  ('solomillo-ternera', 'Solomillo de ternera', 'carne', 'kg', 85, array[]::text[]),
  ('entrecot', 'Entrecot de ternera', 'carne', 'kg', 90, array['lomo alto']::text[]),
  ('ternera-guisar', 'Ternera para guisar', 'carne', 'kg', 90, array['aguja', 'babilla']::text[]),
  ('carne-picada-ternera', 'Carne picada de ternera', 'carne', 'kg', 100, array[]::text[]),
  ('carrillera', 'Carrillera', 'carne', 'kg', 85, array[]::text[]),
  ('rabo-toro', 'Rabo de toro', 'carne', 'kg', 60, array[]::text[]),
  ('cordero-pierna', 'Pierna de cordero', 'carne', 'kg', 70, array[]::text[]),
  ('paletilla-cordero', 'Paletilla de cordero', 'carne', 'kg', 70, array[]::text[]),
  ('costilla-cerdo', 'Costilla de cerdo', 'carne', 'kg', 75, array[]::text[]),
  ('solomillo-cerdo', 'Solomillo de cerdo', 'carne', 'kg', 90, array[]::text[]),
  ('secreto-iberico', 'Secreto ibérico', 'carne', 'kg', 90, array[]::text[]),
  ('presa-iberica', 'Presa ibérica', 'carne', 'kg', 90, array[]::text[]),
  ('lomo-cerdo', 'Lomo de cerdo', 'carne', 'kg', 90, array[]::text[]),
  ('panceta', 'Panceta', 'carne', 'kg', 95, array[]::text[]),
  ('carne-picada-mixta', 'Carne picada mixta', 'carne', 'kg', 100, array[]::text[]),
  ('conejo', 'Conejo', 'carne', 'kg', 75, array[]::text[]),
  ('magret-pato', 'Magret de pato', 'carne', 'kg', 90, array[]::text[]),
  ('hamburguesa-ternera', 'Hamburguesa de ternera', 'carne', 'ud', 100, array[]::text[]),
  ('merluza', 'Merluza', 'pescado', 'kg', 60, array[]::text[]),
  ('bacalao-desalado', 'Bacalao desalado', 'pescado', 'kg', 85, array[]::text[]),
  ('bacalao-fresco', 'Bacalao fresco', 'pescado', 'kg', 65, array[]::text[]),
  ('salmon', 'Salmón', 'pescado', 'kg', 70, array[]::text[]),
  ('atun-rojo', 'Atún rojo', 'pescado', 'kg', 80, array[]::text[]),
  ('bonito', 'Bonito del norte', 'pescado', 'kg', 70, array[]::text[]),
  ('rape', 'Rape', 'pescado', 'kg', 45, array[]::text[]),
  ('dorada', 'Dorada', 'pescado', 'kg', 45, array[]::text[]),
  ('lubina', 'Lubina', 'pescado', 'kg', 45, array[]::text[]),
  ('sardina', 'Sardina', 'pescado', 'kg', 60, array[]::text[]),
  ('boqueron', 'Boquerón', 'pescado', 'kg', 60, array[]::text[]),
  ('calamar', 'Calamar', 'pescado', 'kg', 70, array[]::text[]),
  ('chipiron', 'Chipirón', 'pescado', 'kg', 75, array[]::text[]),
  ('sepia', 'Sepia', 'pescado', 'kg', 60, array[]::text[]),
  ('pulpo', 'Pulpo', 'pescado', 'kg', 50, array[]::text[]),
  ('gamba-roja', 'Gamba roja', 'pescado', 'kg', 50, array[]::text[]),
  ('gamba-blanca', 'Gamba blanca', 'pescado', 'kg', 50, array[]::text[]),
  ('langostino', 'Langostino', 'pescado', 'kg', 50, array[]::text[]),
  ('mejillon', 'Mejillón', 'pescado', 'kg', 35, array[]::text[]),
  ('almeja', 'Almeja', 'pescado', 'kg', 40, array[]::text[]),
  ('berberecho', 'Berberecho', 'pescado', 'kg', 35, array[]::text[]),
  ('navaja', 'Navaja', 'pescado', 'kg', 40, array[]::text[]),
  ('rodaballo', 'Rodaballo', 'pescado', 'kg', 45, array[]::text[]),
  ('pez-espada', 'Pez espada', 'pescado', 'kg', 85, array[]::text[]),
  ('jamon-iberico', 'Jamón ibérico', 'charcuteria', 'kg', 100, array[]::text[]),
  ('jamon-serrano', 'Jamón serrano', 'charcuteria', 'kg', 100, array[]::text[]),
  ('chorizo', 'Chorizo', 'charcuteria', 'kg', 100, array[]::text[]),
  ('salchichon', 'Salchichón', 'charcuteria', 'kg', 100, array[]::text[]),
  ('lomo-embuchado', 'Lomo embuchado', 'charcuteria', 'kg', 100, array[]::text[]),
  ('morcilla', 'Morcilla', 'charcuteria', 'kg', 100, array[]::text[]),
  ('bacon', 'Beicon', 'charcuteria', 'kg', 100, array['bacon']::text[]),
  ('salchicha-fresca', 'Salchicha fresca', 'charcuteria', 'kg', 100, array[]::text[]),
  ('sobrasada', 'Sobrasada', 'charcuteria', 'kg', 100, array[]::text[]),
  ('jamon-cocido', 'Jamón cocido', 'charcuteria', 'kg', 100, array['jamon york']::text[]),
  ('nata-cocinar', 'Nata para cocinar', 'lacteo', 'L', 100, array[]::text[]),
  ('nata-montar', 'Nata para montar', 'lacteo', 'L', 100, array['nata 35']::text[]),
  ('mantequilla', 'Mantequilla', 'lacteo', 'kg', 100, array[]::text[]),
  ('yogur-natural', 'Yogur natural', 'lacteo', 'ud', 100, array[]::text[]),
  ('leche-condensada', 'Leche condensada', 'lacteo', 'kg', 100, array[]::text[]),
  ('espagueti', 'Espagueti', 'pasta', 'kg', 100, array['spaghetti']::text[]),
  ('macarron', 'Macarrón', 'pasta', 'kg', 100, array[]::text[]),
  ('tallarin', 'Tallarín', 'pasta', 'kg', 100, array[]::text[]),
  ('lasana', 'Láminas de lasaña', 'pasta', 'kg', 100, array[]::text[]),
  ('pasta-rellena', 'Pasta fresca rellena', 'pasta', 'kg', 100, array['ravioli']::text[]),
  ('fideo', 'Fideo', 'pasta', 'kg', 100, array[]::text[]),
  ('aceite-girasol', 'Aceite de girasol', 'aceite_otro', 'L', 100, array[]::text[]),
  ('aceite-girasol-ao', 'Aceite de girasol alto oleico', 'aceite_otro', 'L', 100, array['alto oleico']::text[]),
  ('margarina', 'Margarina', 'aceite_otro', 'kg', 100, array[]::text[]),
  ('tomate-triturado', 'Tomate triturado', 'conserva', 'kg', 100, array[]::text[]),
  ('tomate-frito', 'Tomate frito', 'conserva', 'kg', 100, array[]::text[]),
  ('atun-aceite', 'Atún en aceite', 'conserva', 'kg', 75, array[]::text[]),
  ('anchoa', 'Anchoa en aceite', 'conserva', 'kg', 80, array[]::text[]),
  ('piquillo', 'Pimiento del piquillo', 'conserva', 'kg', 85, array[]::text[]),
  ('aceituna-verde', 'Aceituna verde', 'conserva', 'kg', 60, array[]::text[]),
  ('aceituna-negra', 'Aceituna negra', 'conserva', 'kg', 60, array[]::text[]),
  ('alcaparra', 'Alcaparra', 'conserva', 'kg', 70, array[]::text[]),
  ('garbanzo-cocido', 'Garbanzo cocido', 'conserva', 'kg', 65, array[]::text[]),
  ('maiz-dulce', 'Maíz dulce', 'conserva', 'kg', 65, array[]::text[]),
  ('esparrago-blanco', 'Espárrago blanco en conserva', 'conserva', 'kg', 60, array[]::text[]),
  ('sal-fina', 'Sal fina', 'condimento', 'kg', 100, array[]::text[]),
  ('sal-marina', 'Sal marina', 'condimento', 'kg', 100, array['sal gorda']::text[]),
  ('sal-escamas', 'Sal en escamas', 'condimento', 'kg', 100, array['maldon']::text[]),
  ('pimienta-negra', 'Pimienta negra', 'condimento', 'kg', 100, array[]::text[]),
  ('pimenton-dulce', 'Pimentón dulce', 'condimento', 'kg', 100, array[]::text[]),
  ('pimenton-picante', 'Pimentón picante', 'condimento', 'kg', 100, array[]::text[]),
  ('comino', 'Comino', 'condimento', 'kg', 100, array[]::text[]),
  ('oregano', 'Orégano', 'condimento', 'kg', 100, array[]::text[]),
  ('laurel', 'Laurel', 'condimento', 'kg', 100, array[]::text[]),
  ('tomillo', 'Tomillo', 'condimento', 'kg', 100, array[]::text[]),
  ('romero', 'Romero', 'condimento', 'kg', 100, array[]::text[]),
  ('canela', 'Canela', 'condimento', 'kg', 100, array[]::text[]),
  ('azafran', 'Azafrán', 'condimento', 'kg', 100, array[]::text[]),
  ('nuez-moscada', 'Nuez moscada', 'condimento', 'kg', 100, array[]::text[]),
  ('vinagre-jerez', 'Vinagre de Jerez', 'condimento', 'L', 100, array[]::text[]),
  ('vinagre-vino', 'Vinagre de vino', 'condimento', 'L', 100, array[]::text[]),
  ('vinagre-balsamico', 'Vinagre balsámico', 'condimento', 'L', 100, array['balsamico de modena']::text[]),
  ('vinagre-manzana', 'Vinagre de manzana', 'condimento', 'L', 100, array[]::text[]),
  ('mostaza', 'Mostaza', 'condimento', 'kg', 100, array[]::text[]),
  ('salsa-soja', 'Salsa de soja', 'condimento', 'L', 100, array['soja']::text[]),
  ('mayonesa', 'Mayonesa', 'salsa', 'kg', 100, array[]::text[]),
  ('ketchup', 'Kétchup', 'salsa', 'kg', 100, array['ketchup']::text[]),
  ('caldo-pollo', 'Caldo de pollo', 'salsa', 'L', 100, array[]::text[]),
  ('caldo-pescado', 'Caldo de pescado', 'salsa', 'L', 100, array['fumet']::text[]),
  ('salsa-barbacoa', 'Salsa barbacoa', 'salsa', 'kg', 100, array[]::text[]),
  ('alioli', 'Alioli', 'salsa', 'kg', 100, array[]::text[]),
  ('pan-rallado', 'Pan rallado', 'salsa', 'kg', 100, array[]::text[]),
  ('tempura', 'Harina para tempura', 'salsa', 'kg', 100, array[]::text[]),
  ('azucar', 'Azúcar blanco', 'reposteria', 'kg', 100, array['azucar']::text[]),
  ('azucar-moreno', 'Azúcar moreno', 'reposteria', 'kg', 100, array[]::text[]),
  ('azucar-glas', 'Azúcar glas', 'reposteria', 'kg', 100, array[]::text[]),
  ('chocolate-cobertura', 'Chocolate negro de cobertura', 'reposteria', 'kg', 100, array[]::text[]),
  ('cacao-polvo', 'Cacao en polvo', 'reposteria', 'kg', 100, array[]::text[]),
  ('levadura-quimica', 'Levadura química', 'reposteria', 'kg', 100, array[]::text[]),
  ('levadura-fresca', 'Levadura fresca', 'reposteria', 'kg', 100, array[]::text[]),
  ('gelatina-hojas', 'Gelatina en hojas', 'reposteria', 'kg', 100, array[]::text[]),
  ('miel', 'Miel', 'reposteria', 'kg', 100, array[]::text[]),
  ('almendra', 'Almendra marcona', 'reposteria', 'kg', 100, array[]::text[]),
  ('nuez', 'Nuez pelada', 'reposteria', 'kg', 100, array[]::text[]),
  ('pinon', 'Piñón', 'reposteria', 'kg', 100, array[]::text[]),
  ('avellana', 'Avellana', 'reposteria', 'kg', 100, array[]::text[]),
  ('patatas-fritas-cong', 'Patatas fritas congeladas', 'congelado', 'kg', 100, array['patata prefrita']::text[]),
  ('guisante-cong', 'Guisante congelado', 'congelado', 'kg', 100, array[]::text[]),
  ('masa-hojaldre', 'Masa de hojaldre', 'congelado', 'kg', 100, array[]::text[]),
  ('helado-vainilla', 'Helado de vainilla', 'congelado', 'L', 100, array[]::text[]),
  ('croqueta-cong', 'Croqueta congelada', 'congelado', 'kg', 100, array[]::text[]),
  ('gamba-cong', 'Gamba pelada congelada', 'congelado', 'kg', 80, array[]::text[]),
  ('cafe-grano', 'Café en grano', 'cafe', 'kg', 100, array[]::text[]),
  ('cafe-molido', 'Café molido', 'cafe', 'kg', 100, array[]::text[]),
  ('cafe-descafeinado', 'Café descafeinado', 'cafe', 'kg', 100, array[]::text[]),
  ('te-negro', 'Té negro', 'cafe', 'ud', 100, array[]::text[]),
  ('manzanilla', 'Infusión de manzanilla', 'cafe', 'ud', 100, array[]::text[]),
  ('cacao-soluble', 'Cacao soluble', 'cafe', 'kg', 100, array[]::text[]),
  ('agua-50', 'Agua mineral 50 cl', 'bebida', 'ud', 100, array['agua 0.5']::text[]),
  ('agua-150', 'Agua mineral 1,5 L', 'bebida', 'ud', 100, array[]::text[]),
  ('agua-gas', 'Agua con gas', 'bebida', 'ud', 100, array[]::text[]),
  ('refresco-cola', 'Refresco de cola', 'bebida', 'ud', 100, array['cola']::text[]),
  ('refresco-naranja', 'Refresco de naranja', 'bebida', 'ud', 100, array[]::text[]),
  ('refresco-limon', 'Refresco de limón', 'bebida', 'ud', 100, array[]::text[]),
  ('tonica', 'Tónica', 'bebida', 'ud', 100, array[]::text[]),
  ('zumo-naranja', 'Zumo de naranja', 'bebida', 'L', 100, array[]::text[]),
  ('zumo-pina', 'Zumo de piña', 'bebida', 'L', 100, array[]::text[]),
  ('cerveza-sin', 'Cerveza sin alcohol', 'bebida', 'ud', 100, array['cerveza 0,0']::text[]),
  ('cerveza-barril', 'Cerveza de barril', 'cerveza', 'L', 100, array['barril cerveza']::text[]),
  ('cerveza-botellin', 'Cerveza botellín 1/5', 'cerveza', 'ud', 100, array['botellin']::text[]),
  ('cerveza-tercio', 'Cerveza tercio', 'cerveza', 'ud', 100, array[]::text[]),
  ('cerveza-lata', 'Cerveza lata 33 cl', 'cerveza', 'ud', 100, array[]::text[]),
  ('cerveza-artesana', 'Cerveza artesana', 'cerveza', 'ud', 100, array[]::text[]),
  ('vino-tinto-crianza', 'Vino tinto crianza', 'vino', 'ud', 100, array[]::text[]),
  ('vino-tinto-joven', 'Vino tinto joven', 'vino', 'ud', 100, array[]::text[]),
  ('vino-blanco', 'Vino blanco verdejo', 'vino', 'ud', 100, array['verdejo']::text[]),
  ('vino-rosado', 'Vino rosado', 'vino', 'ud', 100, array[]::text[]),
  ('cava', 'Cava brut', 'vino', 'ud', 100, array[]::text[]),
  ('vino-cocina', 'Vino blanco para cocinar', 'vino', 'L', 100, array[]::text[]),
  ('vermut', 'Vermut', 'vino', 'L', 100, array[]::text[]),
  ('sidra', 'Sidra', 'vino', 'ud', 100, array[]::text[]),
  ('ginebra', 'Ginebra', 'licor', 'ud', 100, array['gin']::text[]),
  ('ron', 'Ron', 'licor', 'ud', 100, array[]::text[]),
  ('whisky', 'Whisky', 'licor', 'ud', 100, array[]::text[]),
  ('vodka', 'Vodka', 'licor', 'ud', 100, array[]::text[]),
  ('brandy', 'Brandy', 'licor', 'ud', 100, array['coñac']::text[]),
  ('licor-hierbas', 'Licor de hierbas', 'licor', 'ud', 100, array[]::text[]),
  ('pacharan', 'Pacharán', 'licor', 'ud', 100, array[]::text[]),
  ('orujo', 'Orujo', 'licor', 'ud', 100, array[]::text[]),
  ('tequila', 'Tequila', 'licor', 'ud', 100, array[]::text[]),
  ('lavavajillas', 'Lavavajillas máquina', 'limpieza', 'L', 100, array[]::text[]),
  ('desengrasante', 'Desengrasante', 'limpieza', 'L', 100, array[]::text[]),
  ('lejia', 'Lejía', 'limpieza', 'L', 100, array[]::text[]),
  ('papel-secamanos', 'Papel secamanos', 'limpieza', 'ud', 100, array[]::text[]),
  ('servilletas', 'Servilletas', 'limpieza', 'ud', 100, array[]::text[]),
  ('guantes-nitrilo', 'Guantes de nitrilo', 'limpieza', 'ud', 100, array[]::text[]),
  ('film', 'Film transparente', 'limpieza', 'ud', 100, array[]::text[]),
  ('papel-aluminio', 'Papel de aluminio', 'limpieza', 'ud', 100, array[]::text[]),
  ('bolsas-basura', 'Bolsas de basura', 'limpieza', 'ud', 100, array[]::text[]),
  ('envases-llevar', 'Envases para llevar', 'limpieza', 'ud', 100, array[]::text[])
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, unit = excluded.unit, rend = excluded.rend, aliases = excluded.aliases;
