import type { Locale } from "./types";

// Marketing landing copy (ES / CA) for the professional SaaS site.
// Kept separate from lib/dictionaries.ts (which serves the admin panel).

const es = {
  meta: {
    title: "RESTORA · El control inteligente de tu restaurante",
    description:
      "RESTORA conecta compras, proveedores, escandallos, costes e inventario para darte una visión clara de cómo funciona realmente tu restaurante.",
  },
  nav: {
    home: "Inicio",
    features: "Funcionalidades",
    how: "Cómo funciona",
    pricing: "Precios",
    faq: "Preguntas",
    contact: "Contacto",
    about: "Nosotros",
    theme: "Tema claro / oscuro",
    cta: "Solicitar una demo",
    login: "Entrar",
    trial: "Probar gratis",
  },
  pages: {
    funcionalidades: {
      eyebrow: "Funcionalidades",
      title: "Todo tu restaurante, bajo control.",
      sub: "Compras, proveedores, escandallos, inventario e inteligencia. Cada pieza conectada para que veas el negocio completo, no fragmentos sueltos.",
    },
    comoFunciona: {
      eyebrow: "Cómo funciona",
      title: "De los datos a las decisiones.",
      sub: "RESTORA transforma tu operativa diaria en información útil: qué sube de precio, qué plato pierde margen y qué deberías comprar.",
    },
    precios: {
      eyebrow: "Precios",
      title: "Precios claros, sin sorpresas.",
      sub: "Pruébalo gratis 14 días, sin tarjeta. Después, una suscripción mensual sin permanencia.",
    },
    preguntas: {
      eyebrow: "Preguntas",
      title: "Resolvemos tus dudas.",
      sub: "Lo que más nos preguntan los restaurantes antes de empezar con RESTORA.",
    },
    contacto: {
      eyebrow: "Hablemos",
      title: "Reserva tu demo.",
      sub: "Cuéntanos tu caso y te contactamos en 48 h.",
    },
  },
  home: {
    bandEyebrow: "Hecho para hostelería",
    bandTitle: "Pensado por y para quienes viven la cocina.",
    bandSub: "Menos horas frente a hojas de cálculo. Más tiempo para lo que de verdad importa: tu cocina, tu equipo y tus clientes.",
    exploreEyebrow: "Explora RESTORA",
    exploreTitle: "Descubre cada parte del sistema.",
    exploreSub: "Cada área tiene su propio espacio. Entra en la que más te interese.",
    cards: [
      { key: "funcionalidades", title: "Funcionalidades", desc: "Compras, proveedores, escandallos, inventario e inteligencia en un solo lugar." },
      { key: "como-funciona", title: "Cómo funciona", desc: "Cómo convertimos tus datos operativos en decisiones rentables." },
      { key: "precios", title: "Precios", desc: "14 días gratis, sin tarjeta y sin permanencia." },
      { key: "preguntas", title: "Preguntas", desc: "Resolvemos las dudas más habituales antes de empezar." },
    ],
    heroMetrics: [
      { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%", good: true },
      { label: "Margen bruto", end: 68, decimals: 1, suffix: "%", delta: "+1,8%", good: true },
      { label: "Compras del mes", end: 12840, decimals: 0, suffix: " €", delta: "+4,2%", good: false },
    ],
    heroAlert: { text: "El aceite de oliva ha subido un 14%", action: "Revisar proveedores" },
    capabilities: [
      { title: "Compras", desc: "Controla pedidos y proveedores" },
      { title: "Escandallos", desc: "Calcula costes y optimiza recetas" },
      { title: "Rentabilidad", desc: "Decide con datos reales" },
      { title: "Inventario", desc: "Controla stock, consumo y mermas" },
      { title: "Inteligencia", desc: "Alertas antes de perder margen" },
    ],
    rentabilidad: {
      eyebrow: "Rentabilidad",
      title: "Cada plato, cada compra, cada punto de margen.",
      sub: "RESTORA pone números claros donde antes había intuición: qué plato rinde, qué proveedor se encarece y dónde recuperas margen.",
      metrics: [
        { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%" },
        { label: "Margen bruto", end: 68, decimals: 1, suffix: "%", delta: "+1,8%" },
        { label: "Platos analizados", end: 128, decimals: 0, suffix: "", delta: "+12" },
      ],
    },
    compras: {
      eyebrow: "Compras",
      title: "Compra mejor, con el histórico delante.",
      sub: "Cada pedido, cada precio y cada proveedor en un mismo sitio. RESTORA te enseña cómo evoluciona el coste antes de que te sorprenda la factura.",
    },
  },
  ctaBand: {
    title: "¿Listo para tomar el control de tu restaurante?",
    sub: "Pruébalo gratis 14 días. Sin tarjeta ni compromiso.",
  },
  hero: {
    eyebrow: "Gestión inteligente para restaurantes",
    title: "El control inteligente de tu restaurante.",
    sub: "RESTORA conecta compras, proveedores, escandallos, costes e inventario para darte una visión clara de cómo funciona realmente tu restaurante.",
    ctaPrimary: "Probar gratis 14 días",
    ctaSecondary: "Descubrir cómo funciona",
  },
  problem: {
    eyebrow: "El problema",
    title: "Gestionar un restaurante no debería significar perseguir Excel.",
    sub: "Demasiados datos, demasiados proveedores, demasiadas hojas de cálculo. Es momento de simplificar.",
    note: "Más control. Menos trabajo. Más rentabilidad.",
    items: [
      { icon: "tag", title: "Precios cambiantes", desc: "Los precios de los proveedores varían constantemente y es difícil anticiparse." },
      { icon: "file", title: "Facturas y albaranes dispersos", desc: "Documentos en diferentes formatos y lugares, que requieren mucho tiempo de gestión." },
      { icon: "users", title: "Proveedores desconectados", desc: "Información de proveedores repartida en múltiples canales y sin unificar." },
      { icon: "calc", title: "Escandallos manuales", desc: "Cálculos en Excel que consumen tiempo y generan errores." },
      { icon: "cart", title: "Compras difíciles de comparar", desc: "Sin una visión clara y objetiva de precios, condiciones y proveedores." },
      { icon: "chart", title: "Falta de visibilidad sobre márgenes", desc: "Es difícil saber qué platos son rentables y dónde se pierde dinero." },
      { icon: "clock", title: "Demasiado tiempo en tareas administrativas", desc: "Horas que podrías dedicar a lo más importante: tu cocina y tus clientes." },
    ],
  },
  features: {
    cta: "Descubrir todas las funcionalidades",
  },
  proveedores: {
    eyebrow: "Proveedores",
    title: "Compara, controla y compra mejor.",
    sub: "Toma decisiones basadas en datos con el histórico de precios, la evolución de costes y la comparación entre proveedores. Todo en una sola vista.",
    cta: "Ver proveedores",
  },
  escandallos: {
    eyebrow: "Escandallos y rentabilidad",
    title: "Conoce el coste real de cada plato.",
    sub: "Calcula el coste exacto de tus recetas, gestiona las materias primas y analiza la rentabilidad de tu carta. Con datos reales y actualizados.",
    cta: "Ver escandallos",
  },
  inteligencia: {
    eyebrow: "De los datos a las decisiones",
    title: "La información que necesitas, cuando la necesitas.",
    sub: "RESTORA convierte tus datos operativos en insights reales para que tomes mejores decisiones y aumentes la rentabilidad de tu restaurante.",
    steps: ["Datos", "Análisis", "Insight", "Acción"],
  },
  pricing: {
    trialLabel: "Prueba gratuita",
    trialValue: "14 días",
    trialNote: "con todo RESTORA, sin tarjeta",
    includes: ["Compras y proveedores", "Escandallos y food cost", "Inteligencia y alertas", "Inventario"],
    previewNote:
      "14 días gratis, sin tarjeta. Al terminar la prueba, si quieres seguir, activamos tu suscripción mensual. Sin permanencia.",
    plansBadge: "Planes y precios",
    plansTitle: "Tres planes, un precio claro.",
    plansBody: "Precios mensuales sin IVA; el IVA se añade aparte. Sin permanencia: te das de baja cuando quieras.",
    plans: [
      { name: "Premium", price: "49,90 €", tagline: "Para un solo local.", perks: ["Un local", "Todo lo que incluye la prueba de 14 días"], soon: [] as string[] },
      { name: "Pro", price: "89,90 €", tagline: "Para el restaurante que crece.", perks: ["Todo lo de Premium", "Más funcionalidades"], soon: ["Más de un local (en desarrollo)"] },
      { name: "Max", price: "149,90 €", tagline: "Para grupos más grandes.", perks: ["Todo lo de Pro", "Todas las funcionalidades"], soon: ["Grupos con varios locales (en desarrollo)"] },
    ],
    perMonth: "/mes",
    vatNote: "+ IVA",
    plansNote: "¿Dudas sobre qué plan te encaja? Escríbenos y te lo decimos con franqueza.",
    plansCta: "Escribirnos",
    seeLabel: "Ver precios",
    cta: "Probar gratis 14 días",
  },
  lead: {
    eyebrow: "Demo",
    title: "Solicita tu demo.",
    sub: "Cuéntanos tu caso y te contactamos en 48 h.",
    fName: "Nombre del restaurante",
    fNamePh: "p. ej. Casa Pujol",
    fRole: "Tu rol",
    fCity: "Ciudad",
    fCityPh: "Tarragona",
    fPos: "TPV actual",
    fPosPh: "p. ej. Ágora, Glop, ninguno…",
    fMessage: "¿Alguna pregunta?",
    fMessagePh: "Cuéntanos qué necesitas o pregúntanos lo que quieras (opcional).",
    roles: ["Jefe de cocina", "Gestor / responsable de costes", "Propietario"],
    submit: "Solicitar una demo",
    sending: "Enviando…",
    note: "Sin compromiso. Te escribimos en 48 h.",
    privacyPre: "Al enviar aceptas nuestra",
    privacyLink: "política de privacidad",
    doneTitle: "Solicitud recibida.",
    doneBody: "Gracias. Te contactamos muy pronto para organizar tu demo.",
    errName: "Escribe el nombre del restaurante.",
    errCity: "Escribe la ciudad.",
    errGeneric: "No hemos podido enviar tu solicitud. Inténtalo de nuevo.",
  },
  trust: {
    secure: "Conexión segura · HTTPS",
    secureNote: "Tus datos viajan cifrados y no se venden ni se ceden a otros restaurantes ni a proveedores.",
    rgpd: "Cumplimiento RGPD",
    madeIn: "Hecho en Cataluña",
    eu: "Datos alojados en la UE",
    noTracking: "Sin cookies de rastreo",
  },
  quick: {
    eyebrow: "Contacto rápido",
    title: "¿Solo una pregunta? Sin demo, sin compromiso.",
    sub: "Escríbenos lo que quieras y te respondemos en 48 h, sin comercial de por medio.",
    name: "Tu nombre",
    namePh: "p. ej. Marta",
    email: "Tu email",
    emailPh: "tu@restaurante.com",
    message: "Mensaje",
    messagePh: "¿Qué quieres saber?",
    send: "Enviar mensaje",
    sending: "Enviando…",
    doneTitle: "Recibido.",
    doneBody: "Te respondemos en 48 h a tu correo.",
    errName: "Escribe tu nombre.",
    errEmail: "Escribe un email válido.",
    errMessage: "Escribe tu mensaje.",
    errGeneric: "No hemos podido enviar tu mensaje. Inténtalo de nuevo o escríbenos a hola@restoraapp.com.",
    privacyPre: "Al enviar aceptas nuestra",
    privacyLink: "política de privacidad",
  },
  newsletter: {
    eyebrow: "Recurso gratuito",
    title: "Una checklist de food cost para revisar tu margen cada semana.",
    sub: "Doce comprobaciones sobre compras, escandallos, mermas e inventario, en un PDF de una página listo para imprimir y colgar en el pase.",
    bullets: ["Compras y proveedores", "Escandallos y mermas", "Inventario y consumo"],
    emailPh: "tu@restaurante.com",
    cta: "Quiero la checklist",
    sending: "Enviando…",
    consent: "Acepto recibir la checklist y, de vez en cuando, novedades de RESTORA. Sin spam; te das de baja cuando quieras.",
    doneTitle: "Aquí tienes tu checklist.",
    doneBody: "Descárgala ahora. Te avisaremos también de las novedades de RESTORA.",
    download: "Descargar la checklist (PDF)",
    errEmail: "Escribe un email válido.",
    errConsent: "Marca la casilla para continuar.",
    errGeneric: "No hemos podido registrar tu email. Inténtalo de nuevo.",
  },
  share: {
    label: "Compartir",
    whatsapp: "Compartir por WhatsApp",
    linkedin: "Compartir en LinkedIn",
    email: "Compartir por email",
    copy: "Copiar enlace",
    copied: "Enlace copiado",
    text: "RESTORA · control de food cost y rentabilidad para restaurantes",
    bandTitle: "¿Conoces a alguien que lleve un restaurante?",
    bandSub: "Pásale RESTORA. Un mensaje y ya está.",
  },
  demo: {
    label: "Datos de ejemplo",
    shot: "Captura real de la app, con un restaurante de ejemplo.",
  },
  floating: {
    whatsapp: "Escribirnos por WhatsApp",
    top: "Volver arriba",
  },
  video: {
    eyebrow: "Vídeo de presentación",
    title: "Así se ve RESTORA en una cocina real.",
    sub: "Qué ves cada mañana, cómo entra una compra y cómo el escandallo avisa antes de que pierdas margen.",
    play: "Ver el vídeo",
    soon: "Próximamente",
    soonNote: "Mientras tanto, te lo enseñamos en directo en una demo de 30 minutos con un plato tuyo.",
    cta: "Pedir la demo",
  },
  // Texto alternativo de las fotografías: describe lo que se ve (nunca «imagen generada»). El pie de página avisa de que son ilustrativas.
  images: {
    hero: "Chef emplatando en una cocina profesional",
    problem: "Cocina de restaurante durante el servicio",
    compras: "Producto fresco recibido en cocina",
    recepcion: "Una trabajadora del restaurante revisa la mercancía recién llegada: cajas de fruta, pescado sobre hielo y verduras y carne en un carrito, con la furgoneta del proveedor al fondo",
    escandallos: "Chef terminando un plato",
    profit: "Mesa de restaurante preparada para el servicio",
    closing: "Sala de restaurante al caer la tarde",
    funcionalidades: "Chef trabajando en cocina profesional",
    cocinaAbierta: "Cocina abierta de restaurante en servicio",
    contacto: "Interior de un restaurante",
    preguntas: "Sala de restaurante",
    sobreNosotros: "Mesa de trabajo de una cocina profesional: flores comestibles, cremas y bizcochos preparados para emplatar y, al fondo, el fuego de los fogones",
    salaServicio: "Sala de un restaurante en pleno servicio, con comensales en las mesas y personal de sala atendiendo",
    productoAvisos: "Pantalla «Avisos» de RESTORA: la lubina sube un 9 %, con el coste extra al mes, el food cost de la carta antes y después, el proveedor alternativo más barato y las acciones para valorarlo o darlo por resuelto",
    productoMovil: "RESTORA en el móvil: la pantalla «Hoy» con lo que requiere atención y el food cost del mes frente al objetivo",
  },
  footer: {
    tagline: "La capa de inteligencia de negocio para restaurantes profesionalizados.",
    made: "Hecho en Cataluña",
    colProduct: "Producto",
    colLegal: "Legal",
    colLang: "Idioma",
    privacy: "Privacidad",
    rgpd: "Aviso RGPD",
    legal: "Aviso legal",
    cookies: "Política de cookies",
    about: "Sobre nosotros",
    colContact: "Contacto",
    phone: "Teléfono",
    whatsapp: "WhatsApp",
    whatsappCta: "Escríbenos por WhatsApp",
    social: "Síguenos",
    contact: "hola@restoraapp.com",
    rights: "Todos los derechos reservados.",
    imagesNote: "Imágenes ilustrativas, algunas generadas con IA; no son clientes ni equipos reales.",
    langEs: "Castellano",
    langCa: "Català",
  },
};

export type SiteCopy = typeof es;

const ca: SiteCopy = {
  meta: {
    title: "RESTORA · El control intel·ligent del teu restaurant",
    description:
      "RESTORA connecta compres, proveïdors, escandalls, costos i inventari per donar-te una visió clara de com funciona realment el teu restaurant.",
  },
  nav: {
    home: "Inici",
    features: "Funcionalitats",
    how: "Com funciona",
    pricing: "Preus",
    faq: "Preguntes",
    contact: "Contacte",
    about: "Nosaltres",
    theme: "Tema clar / fosc",
    cta: "Sol·licitar una demo",
    login: "Entra",
    trial: "Prova-ho gratis",
  },
  pages: {
    funcionalidades: {
      eyebrow: "Funcionalitats",
      title: "Tot el teu restaurant, sota control.",
      sub: "Compres, proveïdors, escandalls, inventari i intel·ligència. Cada peça connectada perquè vegis el negoci complet, no fragments solts.",
    },
    comoFunciona: {
      eyebrow: "Com funciona",
      title: "De les dades a les decisions.",
      sub: "RESTORA transforma la teva operativa diària en informació útil: què puja de preu, quin plat perd marge i què hauries de comprar.",
    },
    precios: {
      eyebrow: "Preus",
      title: "Preus clars, sense sorpreses.",
      sub: "Prova-ho gratis 14 dies, sense targeta. Després, una subscripció mensual sense permanència.",
    },
    preguntas: {
      eyebrow: "Preguntes",
      title: "Resolem els teus dubtes.",
      sub: "El que més ens pregunten els restaurants abans de començar amb RESTORA.",
    },
    contacto: {
      eyebrow: "Parlem-ne",
      title: "Reserva la teva demo.",
      sub: "Explica'ns el teu cas i et contactem en 48 h.",
    },
  },
  home: {
    bandEyebrow: "Fet per a l'hostaleria",
    bandTitle: "Pensat per i per a qui viu la cuina.",
    bandSub: "Menys hores davant de fulls de càlcul. Més temps per al que de debò importa: la teva cuina, el teu equip i els teus clients.",
    exploreEyebrow: "Explora RESTORA",
    exploreTitle: "Descobreix cada part del sistema.",
    exploreSub: "Cada àrea té el seu propi espai. Entra a la que més t'interessi.",
    cards: [
      { key: "funcionalidades", title: "Funcionalitats", desc: "Compres, proveïdors, escandalls, inventari i intel·ligència en un sol lloc." },
      { key: "como-funciona", title: "Com funciona", desc: "Com convertim les teves dades operatives en decisions rendibles." },
      { key: "precios", title: "Preus", desc: "14 dies gratis, sense targeta i sense permanència." },
      { key: "preguntas", title: "Preguntes", desc: "Resolem els dubtes més habituals abans de començar." },
    ],
    heroMetrics: [
      { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%", good: true },
      { label: "Marge brut", end: 68, decimals: 1, suffix: "%", delta: "+1,8%", good: true },
      { label: "Compres del mes", end: 12840, decimals: 0, suffix: " €", delta: "+4,2%", good: false },
    ],
    heroAlert: { text: "L'oli d'oliva ha pujat un 14%", action: "Revisar proveïdors" },
    capabilities: [
      { title: "Compres", desc: "Controla comandes i proveïdors" },
      { title: "Escandalls", desc: "Calcula costos i optimitza receptes" },
      { title: "Rendibilitat", desc: "Decideix amb dades reals" },
      { title: "Inventari", desc: "Controla estoc, consum i minves" },
      { title: "Intel·ligència", desc: "Alertes abans de perdre marge" },
    ],
    rentabilidad: {
      eyebrow: "Rendibilitat",
      title: "Cada plat, cada compra, cada punt de marge.",
      sub: "RESTORA posa números clars on abans hi havia intuïció: quin plat rendeix, quin proveïdor s'encareix i on recuperes marge.",
      metrics: [
        { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%" },
        { label: "Marge brut", end: 68, decimals: 1, suffix: "%", delta: "+1,8%" },
        { label: "Plats analitzats", end: 128, decimals: 0, suffix: "", delta: "+12" },
      ],
    },
    compras: {
      eyebrow: "Compres",
      title: "Compra millor, amb l'històric al davant.",
      sub: "Cada comanda, cada preu i cada proveïdor en un mateix lloc. RESTORA et mostra com evoluciona el cost abans que et sorprengui la factura.",
    },
  },
  ctaBand: {
    title: "A punt per prendre el control del teu restaurant?",
    sub: "Prova-ho gratis 14 dies. Sense targeta ni compromís.",
  },
  hero: {
    eyebrow: "Gestió intel·ligent per a restaurants",
    title: "El control intel·ligent del teu restaurant.",
    sub: "RESTORA connecta compres, proveïdors, escandalls, costos i inventari per donar-te una visió clara de com funciona realment el teu restaurant.",
    ctaPrimary: "Prova-ho gratis 14 dies",
    ctaSecondary: "Descobrir com funciona",
  },
  problem: {
    eyebrow: "El problema",
    title: "Gestionar un restaurant no hauria de significar perseguir l'Excel.",
    sub: "Massa dades, massa proveïdors, massa fulls de càlcul. És moment de simplificar.",
    note: "Més control. Menys feina. Més rendibilitat.",
    items: [
      { icon: "tag", title: "Preus canviants", desc: "Els preus dels proveïdors varien constantment i és difícil anticipar-se." },
      { icon: "file", title: "Factures i albarans dispersos", desc: "Documents en diferents formats i llocs, que requereixen molt temps de gestió." },
      { icon: "users", title: "Proveïdors desconnectats", desc: "Informació de proveïdors repartida en múltiples canals i sense unificar." },
      { icon: "calc", title: "Escandalls manuals", desc: "Càlculs a l'Excel que consumeixen temps i generen errors." },
      { icon: "cart", title: "Compres difícils de comparar", desc: "Sense una visió clara i objectiva de preus, condicions i proveïdors." },
      { icon: "chart", title: "Falta de visibilitat sobre marges", desc: "És difícil saber quins plats són rendibles i on es perd diners." },
      { icon: "clock", title: "Massa temps en tasques administratives", desc: "Hores que podries dedicar al més important: la teva cuina i els teus clients." },
    ],
  },
  features: {
    cta: "Descobrir totes les funcionalitats",
  },
  proveedores: {
    eyebrow: "Proveïdors",
    title: "Compara, controla i compra millor.",
    sub: "Pren decisions basades en dades amb l'històric de preus, l'evolució de costos i la comparació entre proveïdors. Tot en una sola vista.",
    cta: "Veure proveïdors",
  },
  escandallos: {
    eyebrow: "Escandalls i rendibilitat",
    title: "Coneix el cost real de cada plat.",
    sub: "Calcula el cost exacte de les teves receptes, gestiona les matèries primeres i analitza la rendibilitat de la teva carta. Amb dades reals i actualitzades.",
    cta: "Veure escandalls",
  },
  inteligencia: {
    eyebrow: "De les dades a les decisions",
    title: "La informació que necessites, quan la necessites.",
    sub: "RESTORA converteix les teves dades operatives en insights reals perquè prenguis millors decisions i augmentis la rendibilitat del teu restaurant.",
    steps: ["Dades", "Anàlisi", "Insight", "Acció"],
  },
  pricing: {
    trialLabel: "Prova gratuïta",
    trialValue: "14 dies",
    trialNote: "amb tot RESTORA, sense targeta",
    includes: ["Compres i proveïdors", "Escandalls i food cost", "Intel·ligència i alertes", "Inventari"],
    previewNote:
      "14 dies gratis, sense targeta. En acabar la prova, si vols continuar, activem la teva subscripció mensual. Sense permanència.",
    plansBadge: "Plans i preus",
    plansTitle: "Tres plans, un preu clar.",
    plansBody: "Preus mensuals sense IVA; l'IVA s'afegeix a part. Sense permanència: et dones de baixa quan vulguis.",
    plans: [
      { name: "Premium", price: "49,90 €", tagline: "Per a un sol local.", perks: ["Un local", "Tot el que inclou la prova de 14 dies"], soon: [] as string[] },
      { name: "Pro", price: "89,90 €", tagline: "Per al restaurant que creix.", perks: ["Tot el de Premium", "Més funcionalitats"], soon: ["Més d'un local (en desenvolupament)"] },
      { name: "Max", price: "149,90 €", tagline: "Per a grups més grans.", perks: ["Tot el de Pro", "Totes les funcionalitats"], soon: ["Grups amb diversos locals (en desenvolupament)"] },
    ],
    perMonth: "/mes",
    vatNote: "+ IVA",
    plansNote: "Dubtes sobre quin pla t'encaixa? Escriu-nos i t'ho diem amb franquesa.",
    plansCta: "Escriu-nos",
    seeLabel: "Veure preus",
    cta: "Prova-ho gratis 14 dies",
  },
  lead: {
    eyebrow: "Demo",
    title: "Sol·licita la teva demo.",
    sub: "Explica'ns el teu cas i et contactem en 48 h.",
    fName: "Nom del restaurant",
    fNamePh: "p. ex. Casa Pujol",
    fRole: "El teu rol",
    fCity: "Ciutat",
    fCityPh: "Tarragona",
    fPos: "TPV actual",
    fPosPh: "p. ex. Àgora, Glop, cap…",
    fMessage: "Alguna pregunta?",
    fMessagePh: "Explica'ns què necessites o pregunta'ns el que vulguis (opcional).",
    roles: ["Cap de cuina", "Gestor / responsable de costos", "Propietari"],
    submit: "Sol·licitar una demo",
    sending: "Enviant…",
    note: "Sense compromís. T'escrivim en 48 h.",
    privacyPre: "En enviar acceptes la nostra",
    privacyLink: "política de privacitat",
    doneTitle: "Sol·licitud rebuda.",
    doneBody: "Gràcies. Et contactem molt aviat per organitzar la teva demo.",
    errName: "Escriu el nom del restaurant.",
    errCity: "Escriu la ciutat.",
    errGeneric: "No hem pogut enviar la teva sol·licitud. Torna-ho a provar.",
  },
  trust: {
    secure: "Connexió segura · HTTPS",
    secureNote: "Les teves dades viatgen xifrades i no es venen ni es cedeixen a altres restaurants ni a proveïdors.",
    rgpd: "Compliment RGPD",
    madeIn: "Fet a Catalunya",
    eu: "Dades allotjades a la UE",
    noTracking: "Sense galetes de seguiment",
  },
  quick: {
    eyebrow: "Contacte ràpid",
    title: "Només una pregunta? Sense demo, sense compromís.",
    sub: "Escriu-nos el que vulguis i et responem en 48 h, sense comercial pel mig.",
    name: "El teu nom",
    namePh: "p. ex. Marta",
    email: "El teu email",
    emailPh: "tu@restaurant.com",
    message: "Missatge",
    messagePh: "Què vols saber?",
    send: "Enviar missatge",
    sending: "Enviant…",
    doneTitle: "Rebut.",
    doneBody: "Et responem en 48 h al teu correu.",
    errName: "Escriu el teu nom.",
    errEmail: "Escriu un email vàlid.",
    errMessage: "Escriu el teu missatge.",
    errGeneric: "No hem pogut enviar el teu missatge. Torna-ho a provar o escriu-nos a hola@restoraapp.com.",
    privacyPre: "En enviar acceptes la nostra",
    privacyLink: "política de privacitat",
  },
  newsletter: {
    eyebrow: "Recurs gratuït",
    title: "Una checklist de food cost per revisar el teu marge cada setmana.",
    sub: "Dotze comprovacions sobre compres, escandalls, minves i inventari, en un PDF d'una pàgina a punt per imprimir i penjar al pas.",
    bullets: ["Compres i proveïdors", "Escandalls i minves", "Inventari i consum"],
    emailPh: "tu@restaurant.com",
    cta: "Vull la checklist",
    sending: "Enviant…",
    consent: "Accepto rebre la checklist i, de tant en tant, novetats de RESTORA. Sense spam; et dones de baixa quan vulguis.",
    doneTitle: "Aquí tens la teva checklist.",
    doneBody: "Descarrega-la ara. També t'avisarem de les novetats de RESTORA.",
    download: "Descarregar la checklist (PDF)",
    errEmail: "Escriu un email vàlid.",
    errConsent: "Marca la casella per continuar.",
    errGeneric: "No hem pogut registrar el teu email. Torna-ho a provar.",
  },
  share: {
    label: "Compartir",
    whatsapp: "Compartir per WhatsApp",
    linkedin: "Compartir a LinkedIn",
    email: "Compartir per correu",
    copy: "Copiar l'enllaç",
    copied: "Enllaç copiat",
    text: "RESTORA · control de food cost i rendibilitat per a restaurants",
    bandTitle: "Coneixes algú que porti un restaurant?",
    bandSub: "Passa-li RESTORA. Un missatge i ja està.",
  },
  demo: {
    label: "Dades d'exemple",
    shot: "Captura real de l'app, amb un restaurant d'exemple.",
  },
  floating: {
    whatsapp: "Escriure'ns per WhatsApp",
    top: "Tornar a dalt",
  },
  video: {
    eyebrow: "Vídeo de presentació",
    title: "Així es veu RESTORA en una cuina real.",
    sub: "Què veus cada matí, com entra una compra i com l'escandall avisa abans que perdis marge.",
    play: "Veure el vídeo",
    soon: "Properament",
    soonNote: "Mentrestant, t'ho ensenyem en directe en una demo de 30 minuts amb un plat teu.",
    cta: "Demanar la demo",
  },
  images: {
    hero: "Xef emplatant en una cuina professional",
    problem: "Cuina de restaurant durant el servei",
    compras: "Producte fresc rebut a la cuina",
    recepcion: "Una treballadora del restaurant revisa la mercaderia que acaba d'arribar: caixes de fruita, peix sobre gel i verdures i carn en un carretó, amb la furgoneta del proveïdor al fons",
    escandallos: "Xef acabant un plat",
    profit: "Taula de restaurant preparada per al servei",
    closing: "Sala de restaurant al cap vespre",
    funcionalidades: "Xef treballant en una cuina professional",
    cocinaAbierta: "Cuina oberta de restaurant en servei",
    contacto: "Interior d'un restaurant",
    preguntas: "Sala de restaurant",
    sobreNosotros: "Taula de treball d'una cuina professional: flors comestibles, cremes i bescuits preparats per emplatar i, al fons, el foc dels fogons",
    salaServicio: "Sala d'un restaurant en ple servei, amb comensals a les taules i personal de sala atenent",
    productoAvisos: "Pantalla «Avisos» de RESTORA: el llobarro puja un 9 %, amb el cost extra al mes, el food cost de la carta abans i després, el proveïdor alternatiu més barat i les accions per valorar-ho o donar-ho per resolt",
    productoMovil: "RESTORA al mòbil: la pantalla «Hoy» amb el que requereix atenció i el food cost del mes davant de l'objectiu",
  },
  footer: {
    tagline: "La capa d'intel·ligència de negoci per a restaurants professionalitzats.",
    made: "Fet a Catalunya",
    colProduct: "Producte",
    colLegal: "Legal",
    colLang: "Idioma",
    privacy: "Privacitat",
    rgpd: "Avís RGPD",
    legal: "Avís legal",
    cookies: "Política de galetes",
    about: "Sobre nosaltres",
    colContact: "Contacte",
    phone: "Telèfon",
    whatsapp: "WhatsApp",
    whatsappCta: "Escriu-nos per WhatsApp",
    social: "Segueix-nos",
    contact: "hola@restoraapp.com",
    rights: "Tots els drets reservats.",
    imagesNote: "Imatges il·lustratives, algunes generades amb IA; no són clients ni equips reals.",
    langEs: "Castellano",
    langCa: "Català",
  },
};

const copies: Record<Locale, SiteCopy> = { es, ca };

export function getSiteCopy(locale: Locale): SiteCopy {
  return copies[locale];
}
