import type { Locale } from "./types";

// Marketing landing copy (ES / CA) for the professional SaaS site.
// Kept separate from lib/dictionaries.ts (which serves the admin panel).

const es = {
  meta: {
    title: "RESTORA · El control inteligente de tu restaurante",
    description:
      "RESTORA conecta compras, proveedores, escandallos, costes e inventario para darte una visión clara de cómo funciona realmente tu restaurante.",
  },
  nav: {
    home: "Inicio",
    features: "Funcionalidades",
    how: "Cómo funciona",
    pricing: "Precios",
    faq: "Preguntas",
    contact: "Contacto",
    cta: "Solicitar una demo",
  },
  pages: {
    funcionalidades: {
      eyebrow: "Funcionalidades",
      title: "Todo tu restaurante, bajo control.",
      sub: "Compras, proveedores, escandallos, inventario e inteligencia. Cada pieza conectada para que veas el negocio completo, no fragmentos sueltos.",
    },
    comoFunciona: {
      eyebrow: "Cómo funciona",
      title: "De los datos a las decisiones.",
      sub: "RESTORA transforma tu operativa diaria en información útil: qué sube de precio, qué plato pierde margen y qué deberías comprar.",
    },
    precios: {
      eyebrow: "Precios",
      title: "Precios claros, sin sorpresas.",
      sub: "Elige el plan que encaja con tu restaurante. Aún en vista previa: hoy reservas plaza de socio fundador, sin coste.",
    },
    preguntas: {
      eyebrow: "Preguntas",
      title: "Resolvemos tus dudas.",
      sub: "Lo que más nos preguntan los restaurantes antes de empezar con RESTORA.",
    },
    contacto: {
      eyebrow: "Hablemos",
      title: "Reserva tu demo y tu plaza.",
      sub: "Cuéntanos tu caso y te contactamos en 48 h. Plazas limitadas a los primeros restaurantes de Cataluña.",
    },
  },
  home: {
    bandEyebrow: "Hecho para hostelería",
    bandTitle: "Pensado por y para quienes viven la cocina.",
    bandSub: "Menos horas frente a hojas de cálculo. Más tiempo para lo que de verdad importa: tu cocina, tu equipo y tus clientes.",
    exploreEyebrow: "Explora RESTORA",
    exploreTitle: "Descubre cada parte del sistema.",
    exploreSub: "Cada área tiene su propio espacio. Entra en la que más te interese.",
    cards: [
      { key: "funcionalidades", title: "Funcionalidades", desc: "Compras, proveedores, escandallos, inventario e inteligencia en un solo lugar." },
      { key: "como-funciona", title: "Cómo funciona", desc: "Cómo convertimos tus datos operativos en decisiones rentables." },
      { key: "precios", title: "Precios", desc: "Desde 89 €/mes y una oferta exclusiva para socios fundadores." },
      { key: "preguntas", title: "Preguntas", desc: "Resolvemos las dudas más habituales antes de empezar." },
    ],
    heroMetrics: [
      { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%", good: true },
      { label: "Margen bruto", end: 68, decimals: 1, suffix: "%", delta: "+1,8%", good: true },
      { label: "Compras del mes", end: 12840, decimals: 0, suffix: " €", delta: "+4,2%", good: false },
    ],
    heroAlert: { text: "El aceite de oliva ha subido un 14%", action: "Revisar proveedores" },
    capabilities: [
      { title: "Compras", desc: "Controla pedidos y proveedores" },
      { title: "Escandallos", desc: "Calcula costes y optimiza recetas" },
      { title: "Rentabilidad", desc: "Decide con datos reales" },
      { title: "Inventario", desc: "Evita roturas y desperdicio" },
      { title: "Inteligencia", desc: "Alertas antes de perder margen" },
    ],
    rentabilidad: {
      eyebrow: "Rentabilidad",
      title: "Cada plato, cada compra, cada punto de margen.",
      sub: "RESTORA pone números claros donde antes había intuición: qué plato rinde, qué proveedor se encarece y dónde recuperas margen.",
      metrics: [
        { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%" },
        { label: "Margen bruto", end: 68, decimals: 1, suffix: "%", delta: "+1,8%" },
        { label: "Platos analizados", end: 128, decimals: 0, suffix: "", delta: "+12" },
      ],
    },
    compras: {
      eyebrow: "Compras",
      title: "Compra mejor, con el histórico delante.",
      sub: "Cada pedido, cada precio y cada proveedor en un mismo sitio. RESTORA te enseña cómo evoluciona el coste antes de que te sorprenda la factura.",
    },
  },
  ctaBand: {
    title: "¿Listo para tomar el control de tu restaurante?",
    sub: "Reserva tu plaza de socio fundador. Sin coste ni compromiso.",
  },
  hero: {
    eyebrow: "Gestión inteligente para restaurantes",
    title: "El control inteligente de tu restaurante.",
    sub: "RESTORA conecta compras, proveedores, escandallos, costes e inventario para darte una visión clara de cómo funciona realmente tu restaurante.",
    ctaPrimary: "Solicitar una demo",
    ctaSecondary: "Descubrir cómo funciona",
    chips: ["Compras", "Proveedores", "Costes", "Rentabilidad", "Automatización"],
    badge: "Vista previa · el pago se abre pronto",
  },
  problem: {
    eyebrow: "El problema",
    title: "Gestionar un restaurante no debería significar perseguir Excel.",
    sub: "Demasiados datos, demasiados proveedores, demasiadas hojas de cálculo. Es momento de simplificar.",
    note: "Más control. Menos trabajo. Más rentabilidad.",
    items: [
      { icon: "tag", title: "Precios cambiantes", desc: "Los precios de los proveedores varían constantemente y es difícil anticiparse." },
      { icon: "file", title: "Facturas y albaranes dispersos", desc: "Documentos en diferentes formatos y lugares, que requieren mucho tiempo de gestión." },
      { icon: "users", title: "Proveedores desconectados", desc: "Información de proveedores repartida en múltiples canales y sin unificar." },
      { icon: "calc", title: "Escandallos manuales", desc: "Cálculos en Excel que consumen tiempo y generan errores." },
      { icon: "cart", title: "Compras difíciles de comparar", desc: "Sin una visión clara y objetiva de precios, condiciones y proveedores." },
      { icon: "chart", title: "Falta de visibilidad sobre márgenes", desc: "Es difícil saber qué platos son rentables y dónde se pierde dinero." },
      { icon: "clock", title: "Demasiado tiempo en tareas administrativas", desc: "Horas que podrías dedicar a lo más importante: tu cocina y tus clientes." },
    ],
  },
  features: {
    eyebrow: "Funcionalidades",
    title: "Todo lo que necesitas, en un solo lugar.",
    sub: "Una plataforma completa para gestionar compras, proveedores, costes, escandallos, inventario y mucho más. Todo integrado, todo conectado, todo bajo control.",
    cta: "Descubrir todas las funcionalidades",
    cards: [
      { icon: "cart", title: "Compras", items: ["Histórico de precios", "Comparación de proveedores", "Evolución de costes", "Control de compras", "Recomendaciones"] },
      { icon: "truck", title: "Proveedores", items: ["Fichas de proveedor", "Productos", "Precios históricos", "Comparativas", "Pedidos"] },
      { icon: "dish", title: "Escandallos", items: ["Coste real por plato", "Materias primas", "Márgenes", "Actualización de costes"] },
      { icon: "box", title: "Inventario", items: ["Stock", "Consumo", "Variaciones", "Control de producto"] },
      { icon: "spark", title: "Inteligencia", items: ["Alertas", "Detección de anomalías", "Previsión", "Recomendaciones"] },
      { icon: "bolt", title: "Automatización", items: ["Pedidos", "Flujos de trabajo", "Notificaciones", "Automatizaciones"] },
    ],
  },
  proveedores: {
    eyebrow: "Proveedores",
    title: "Compara, controla y compra mejor.",
    sub: "Toma decisiones basadas en datos con el histórico de precios, la evolución de costes y la comparación entre proveedores. Todo en una sola vista.",
    cta: "Ver proveedores",
  },
  escandallos: {
    eyebrow: "Escandallos y rentabilidad",
    title: "Conoce el coste real de cada plato.",
    sub: "Calcula el coste exacto de tus recetas, gestiona las materias primas y analiza la rentabilidad de tu carta. Con datos reales y actualizados.",
    cta: "Ver escandallos",
  },
  inteligencia: {
    eyebrow: "De los datos a las decisiones",
    title: "La información que necesitas, cuando la necesitas.",
    sub: "RESTORA convierte tus datos operativos en insights reales para que tomes mejores decisiones y aumentes la rentabilidad de tu restaurante.",
    steps: ["Datos", "Análisis", "Insight", "Acción"],
    insight: "El precio del tomate ha aumentado un 12% en las últimas 6 semanas.",
    insightAction: "Revisa proveedores alternativos",
  },
  conexion: {
    eyebrow: "TPV + Escandallos",
    title: "Conecta lo que vendes con lo que compras.",
    sub: "Cuando tu TPV está conectado con los escandallos, RESTORA relaciona ventas, recetas, materias primas y compras para calcular el consumo real y anticipar tus necesidades de compra.",
    soon: "Próximamente",
    inputs: ["TPV", "Ventas", "Recetas", "Materias primas", "Compras"],
    outputs: ["Consumo estimado", "Necesidades de compra"],
  },
  pricing: {
    eyebrow: "Precios",
    title: "Un precio claro. Sin letra pequeña.",
    sub: "Todo RESTORA en un único plan que crece contigo. Sin permanencia.",
    fromLabel: "Desde",
    price: "89 €",
    period: "/mes",
    includes: ["Compras y proveedores", "Escandallos y food cost", "Inteligencia y alertas", "Inventario"],
    previewNote:
      "Vista previa: el pago aún no está activo. Hoy reservas tu plaza de socio fundador, sin coste ni compromiso.",
    founderBadge: "Oferta exclusiva · plazas limitadas",
    founderTitle: "Programa Socios Fundadores",
    founderBody:
      "Para los primeros restaurantes de Cataluña que construyen RESTORA con nosotros.",
    founderPerks: [
      "Precio especial de por vida",
      "Acceso prioritario y onboarding dedicado",
      "Influencia directa en el producto",
    ],
    cta: "Reservar mi plaza",
  },
  faq: {
    eyebrow: "Preguntas",
    title: "Preguntas frecuentes",
    sub: "Lo que más nos preguntan los restaurantes.",
    items: [
      { q: "¿Ya puedo contratar RESTORA?", a: "Todavía no. Esto es una vista previa de lo que estamos construyendo: puedes reservar plaza como socio fundador y te avisamos en cuanto abramos acceso." },
      { q: "¿Tengo que cambiar mi TPV?", a: "No. RESTORA es la capa de inteligencia por encima de lo que ya usas. Empiezas con una foto del albarán, sin cambiar tu operativa." },
      { q: "¿Mis datos son privados?", a: "Sí. Tus datos son tuyos. El benchmark sectorial es siempre anónimo y agregado: nadie ve los números de tu restaurante." },
      { q: "¿Cuánto costará?", a: "Los precios que ves son orientativos (Base, Pro y Grupo). Los socios fundadores tendrán precio y condiciones especiales." },
      { q: "¿Cuándo estará disponible?", a: "Estamos arrancando con los primeros restaurantes de Cataluña. Déjanos tus datos y serás de los primeros en entrar." },
    ],
  },
  lead: {
    eyebrow: "Socios fundadores",
    title: "Solicita tu demo y reserva plaza.",
    sub: "Plazas limitadas a los primeros restaurantes de Cataluña. Cuéntanos tu caso y te contactamos.",
    fName: "Nombre del restaurante",
    fNamePh: "p. ej. Casa Pujol",
    fRole: "Tu rol",
    fCity: "Ciudad",
    fCityPh: "Tarragona",
    fPos: "TPV actual",
    fPosPh: "p. ej. Ágora, Glop, ninguno…",
    fMessage: "¿Alguna pregunta?",
    fMessagePh: "Cuéntanos qué necesitas o pregúntanos lo que quieras (opcional).",
    roles: ["Jefe de cocina", "Gestor / responsable de costes", "Propietario"],
    submit: "Solicitar acceso",
    sending: "Enviando…",
    note: "Sin compromiso. Te escribimos en 48 h.",
    doneTitle: "Estás en la lista.",
    doneBody: "Gracias. Te contactamos muy pronto para tu acceso de socio fundador.",
    errName: "Escribe el nombre del restaurante.",
    errCity: "Escribe la ciudad.",
    errGeneric: "No hemos podido enviar tu solicitud. Inténtalo de nuevo.",
  },
  footer: {
    tagline: "La capa de inteligencia de negocio para restaurantes profesionalizados.",
    made: "Hecho en Cataluña",
    colProduct: "Producto",
    colLegal: "Legal",
    colLang: "Idioma",
    privacy: "Privacidad",
    rgpd: "Aviso RGPD",
    contact: "hola@restoraapp.com",
    rights: "Todos los derechos reservados.",
    langEs: "Castellano",
    langCa: "Català",
  },
};

export type SiteCopy = typeof es;

const ca: SiteCopy = {
  meta: {
    title: "RESTORA · El control intel·ligent del teu restaurant",
    description:
      "RESTORA connecta compres, proveïdors, escandalls, costos i inventari per donar-te una visió clara de com funciona realment el teu restaurant.",
  },
  nav: {
    home: "Inici",
    features: "Funcionalitats",
    how: "Com funciona",
    pricing: "Preus",
    faq: "Preguntes",
    contact: "Contacte",
    cta: "Sol·licitar una demo",
  },
  pages: {
    funcionalidades: {
      eyebrow: "Funcionalitats",
      title: "Tot el teu restaurant, sota control.",
      sub: "Compres, proveïdors, escandalls, inventari i intel·ligència. Cada peça connectada perquè vegis el negoci complet, no fragments solts.",
    },
    comoFunciona: {
      eyebrow: "Com funciona",
      title: "De les dades a les decisions.",
      sub: "RESTORA transforma la teva operativa diària en informació útil: què puja de preu, quin plat perd marge i què hauries de comprar.",
    },
    precios: {
      eyebrow: "Preus",
      title: "Preus clars, sense sorpreses.",
      sub: "Tria el pla que encaixa amb el teu restaurant. Encara en vista prèvia: avui reserves plaça de soci fundador, sense cost.",
    },
    preguntas: {
      eyebrow: "Preguntes",
      title: "Resolem els teus dubtes.",
      sub: "El que més ens pregunten els restaurants abans de començar amb RESTORA.",
    },
    contacto: {
      eyebrow: "Parlem-ne",
      title: "Reserva la teva demo i la teva plaça.",
      sub: "Explica'ns el teu cas i et contactem en 48 h. Places limitades als primers restaurants de Catalunya.",
    },
  },
  home: {
    bandEyebrow: "Fet per a l'hostaleria",
    bandTitle: "Pensat per i per a qui viu la cuina.",
    bandSub: "Menys hores davant de fulls de càlcul. Més temps per al que de debò importa: la teva cuina, el teu equip i els teus clients.",
    exploreEyebrow: "Explora RESTORA",
    exploreTitle: "Descobreix cada part del sistema.",
    exploreSub: "Cada àrea té el seu propi espai. Entra a la que més t'interessi.",
    cards: [
      { key: "funcionalidades", title: "Funcionalitats", desc: "Compres, proveïdors, escandalls, inventari i intel·ligència en un sol lloc." },
      { key: "como-funciona", title: "Com funciona", desc: "Com convertim les teves dades operatives en decisions rendibles." },
      { key: "precios", title: "Preus", desc: "Des de 89 €/mes i una oferta exclusiva per a socis fundadors." },
      { key: "preguntas", title: "Preguntes", desc: "Resolem els dubtes més habituals abans de començar." },
    ],
    heroMetrics: [
      { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%", good: true },
      { label: "Marge brut", end: 68, decimals: 1, suffix: "%", delta: "+1,8%", good: true },
      { label: "Compres del mes", end: 12840, decimals: 0, suffix: " €", delta: "+4,2%", good: false },
    ],
    heroAlert: { text: "L'oli d'oliva ha pujat un 14%", action: "Revisar proveïdors" },
    capabilities: [
      { title: "Compres", desc: "Controla comandes i proveïdors" },
      { title: "Escandalls", desc: "Calcula costos i optimitza receptes" },
      { title: "Rendibilitat", desc: "Decideix amb dades reals" },
      { title: "Inventari", desc: "Evita ruptures i malbaratament" },
      { title: "Intel·ligència", desc: "Alertes abans de perdre marge" },
    ],
    rentabilidad: {
      eyebrow: "Rendibilitat",
      title: "Cada plat, cada compra, cada punt de marge.",
      sub: "RESTORA posa números clars on abans hi havia intuïció: quin plat rendeix, quin proveïdor s'encareix i on recuperes marge.",
      metrics: [
        { label: "Food cost", end: 31.4, decimals: 1, suffix: "%", delta: "−2,4%" },
        { label: "Marge brut", end: 68, decimals: 1, suffix: "%", delta: "+1,8%" },
        { label: "Plats analitzats", end: 128, decimals: 0, suffix: "", delta: "+12" },
      ],
    },
    compras: {
      eyebrow: "Compres",
      title: "Compra millor, amb l'històric al davant.",
      sub: "Cada comanda, cada preu i cada proveïdor en un mateix lloc. RESTORA et mostra com evoluciona el cost abans que et sorprengui la factura.",
    },
  },
  ctaBand: {
    title: "A punt per prendre el control del teu restaurant?",
    sub: "Reserva la teva plaça de soci fundador. Sense cost ni compromís.",
  },
  hero: {
    eyebrow: "Gestió intel·ligent per a restaurants",
    title: "El control intel·ligent del teu restaurant.",
    sub: "RESTORA connecta compres, proveïdors, escandalls, costos i inventari per donar-te una visió clara de com funciona realment el teu restaurant.",
    ctaPrimary: "Sol·licitar una demo",
    ctaSecondary: "Descobrir com funciona",
    chips: ["Compres", "Proveïdors", "Costos", "Rendibilitat", "Automatització"],
    badge: "Vista prèvia · el pagament s'obre aviat",
  },
  problem: {
    eyebrow: "El problema",
    title: "Gestionar un restaurant no hauria de significar perseguir l'Excel.",
    sub: "Massa dades, massa proveïdors, massa fulls de càlcul. És moment de simplificar.",
    note: "Més control. Menys feina. Més rendibilitat.",
    items: [
      { icon: "tag", title: "Preus canviants", desc: "Els preus dels proveïdors varien constantment i és difícil anticipar-se." },
      { icon: "file", title: "Factures i albarans dispersos", desc: "Documents en diferents formats i llocs, que requereixen molt temps de gestió." },
      { icon: "users", title: "Proveïdors desconnectats", desc: "Informació de proveïdors repartida en múltiples canals i sense unificar." },
      { icon: "calc", title: "Escandalls manuals", desc: "Càlculs a l'Excel que consumeixen temps i generen errors." },
      { icon: "cart", title: "Compres difícils de comparar", desc: "Sense una visió clara i objectiva de preus, condicions i proveïdors." },
      { icon: "chart", title: "Falta de visibilitat sobre marges", desc: "És difícil saber quins plats són rendibles i on es perd diners." },
      { icon: "clock", title: "Massa temps en tasques administratives", desc: "Hores que podries dedicar al més important: la teva cuina i els teus clients." },
    ],
  },
  features: {
    eyebrow: "Funcionalitats",
    title: "Tot el que necessites, en un sol lloc.",
    sub: "Una plataforma completa per gestionar compres, proveïdors, costos, escandalls, inventari i molt més. Tot integrat, tot connectat, tot sota control.",
    cta: "Descobrir totes les funcionalitats",
    cards: [
      { icon: "cart", title: "Compres", items: ["Històric de preus", "Comparació de proveïdors", "Evolució de costos", "Control de compres", "Recomanacions"] },
      { icon: "truck", title: "Proveïdors", items: ["Fitxes de proveïdor", "Productes", "Preus històrics", "Comparatives", "Comandes"] },
      { icon: "dish", title: "Escandalls", items: ["Cost real per plat", "Matèries primeres", "Marges", "Actualització de costos"] },
      { icon: "box", title: "Inventari", items: ["Estoc", "Consum", "Variacions", "Control de producte"] },
      { icon: "spark", title: "Intel·ligència", items: ["Alertes", "Detecció d'anomalies", "Previsió", "Recomanacions"] },
      { icon: "bolt", title: "Automatització", items: ["Comandes", "Fluxos de treball", "Notificacions", "Automatitzacions"] },
    ],
  },
  proveedores: {
    eyebrow: "Proveïdors",
    title: "Compara, controla i compra millor.",
    sub: "Pren decisions basades en dades amb l'històric de preus, l'evolució de costos i la comparació entre proveïdors. Tot en una sola vista.",
    cta: "Veure proveïdors",
  },
  escandallos: {
    eyebrow: "Escandalls i rendibilitat",
    title: "Coneix el cost real de cada plat.",
    sub: "Calcula el cost exacte de les teves receptes, gestiona les matèries primeres i analitza la rendibilitat de la teva carta. Amb dades reals i actualitzades.",
    cta: "Veure escandalls",
  },
  inteligencia: {
    eyebrow: "De les dades a les decisions",
    title: "La informació que necessites, quan la necessites.",
    sub: "RESTORA converteix les teves dades operatives en insights reals perquè prenguis millors decisions i augmentis la rendibilitat del teu restaurant.",
    steps: ["Dades", "Anàlisi", "Insight", "Acció"],
    insight: "El preu del tomàquet ha augmentat un 12% en les últimes 6 setmanes.",
    insightAction: "Revisa proveïdors alternatius",
  },
  conexion: {
    eyebrow: "TPV + Escandalls",
    title: "Connecta el que vens amb el que compres.",
    sub: "Quan el teu TPV està connectat amb els escandalls, RESTORA relaciona vendes, receptes, matèries primeres i compres per calcular el consum real i anticipar les teves necessitats de compra.",
    soon: "Properament",
    inputs: ["TPV", "Vendes", "Receptes", "Matèries primeres", "Compres"],
    outputs: ["Consum estimat", "Necessitats de compra"],
  },
  pricing: {
    eyebrow: "Preus",
    title: "Un preu clar. Sense lletra petita.",
    sub: "Tot RESTORA en un únic pla que creix amb tu. Sense permanència.",
    fromLabel: "Des de",
    price: "89 €",
    period: "/mes",
    includes: ["Compres i proveïdors", "Escandalls i food cost", "Intel·ligència i alertes", "Inventari"],
    previewNote:
      "Vista prèvia: el pagament encara no està actiu. Avui reserves la teva plaça de soci fundador, sense cost ni compromís.",
    founderBadge: "Oferta exclusiva · places limitades",
    founderTitle: "Programa Socis Fundadors",
    founderBody:
      "Per als primers restaurants de Catalunya que construeixen RESTORA amb nosaltres.",
    founderPerks: [
      "Preu especial de per vida",
      "Accés prioritari i onboarding dedicat",
      "Influència directa en el producte",
    ],
    cta: "Reservar la meva plaça",
  },
  faq: {
    eyebrow: "Preguntes",
    title: "Preguntes freqüents",
    sub: "El que més ens pregunten els restaurants.",
    items: [
      { q: "Ja puc contractar RESTORA?", a: "Encara no. Això és una vista prèvia del que estem construint: pots reservar plaça com a soci fundador i t'avisem quan obrim l'accés." },
      { q: "He de canviar el meu TPV?", a: "No. RESTORA és la capa d'intel·ligència per sobre del que ja fas servir. Comences amb una foto de l'albarà, sense canviar la teva operativa." },
      { q: "Les meves dades són privades?", a: "Sí. Les teves dades són teves. El benchmark sectorial és sempre anònim i agregat: ningú veu els números del teu restaurant." },
      { q: "Quant costarà?", a: "Els preus que veus són orientatius (Base, Pro i Grup). Els socis fundadors tindran preu i condicions especials." },
      { q: "Quan estarà disponible?", a: "Estem arrancant amb els primers restaurants de Catalunya. Deixa'ns les teves dades i seràs dels primers a entrar." },
    ],
  },
  lead: {
    eyebrow: "Socis fundadors",
    title: "Sol·licita la teva demo i reserva plaça.",
    sub: "Places limitades als primers restaurants de Catalunya. Explica'ns el teu cas i et contactem.",
    fName: "Nom del restaurant",
    fNamePh: "p. ex. Casa Pujol",
    fRole: "El teu rol",
    fCity: "Ciutat",
    fCityPh: "Tarragona",
    fPos: "TPV actual",
    fPosPh: "p. ex. Àgora, Glop, cap…",
    fMessage: "Alguna pregunta?",
    fMessagePh: "Explica'ns què necessites o pregunta'ns el que vulguis (opcional).",
    roles: ["Cap de cuina", "Gestor / responsable de costos", "Propietari"],
    submit: "Sol·licitar accés",
    sending: "Enviant…",
    note: "Sense compromís. T'escrivim en 48 h.",
    doneTitle: "Ja ets a la llista.",
    doneBody: "Gràcies. Et contactem molt aviat per al teu accés de soci fundador.",
    errName: "Escriu el nom del restaurant.",
    errCity: "Escriu la ciutat.",
    errGeneric: "No hem pogut enviar la teva sol·licitud. Torna-ho a provar.",
  },
  footer: {
    tagline: "La capa d'intel·ligència de negoci per a restaurants professionalitzats.",
    made: "Fet a Catalunya",
    colProduct: "Producte",
    colLegal: "Legal",
    colLang: "Idioma",
    privacy: "Privacitat",
    rgpd: "Avís RGPD",
    contact: "hola@restoraapp.com",
    rights: "Tots els drets reservats.",
    langEs: "Castellano",
    langCa: "Català",
  },
};

const copies: Record<Locale, SiteCopy> = { es, ca };

export function getSiteCopy(locale: Locale): SiteCopy {
  return copies[locale];
}
